可以使用 `assert` 函数进行断言。程序在执行到 `assert` 时会判断其中的逻辑条件表达式参数是否为 true。如果条件判断为 true，代码运行会继续进行。如果条件判断为 false，程序将会终止。通常，在为程序加入并触发断言后，Xcode 会精确定位到异常代码段，并反馈异常信息等修改 bug 必须的调试信息。标准的断言使用格式如下：

```swift
var UseDate = -1
// 不支持字符串插值，否则会弹出异常
assert(UseDate <= 0, "超出试用期，不能启动程序")
// 当 UseDate > 0 时，编译器会提示异常 EXC_BAD_INSTRUCTION
// 并且在程序输出窗口提示：asserting failed：超出试用期，不能启动程序：file/Volumes/MacBak/work/SwiftInAction/SwiftInAction-002-004/SwiftInAction-002-004/main.swift, line 29
// application main
```

`assert` 函数的定义如下：

```swift
public func assert(_ condition: @autoclosure () -> Bool, _ message: @autoclosure () -> String = String(), file: StaticString = #file, line: UInt = #line)
```

通过查看其定义单元中的代码注释，系统在断言的源代码中加入了类似 `#if NDEBUG` 这样的编译字，使其只能用于 debug 期，当你在发布 release 版本或者更新版的时候，编译器会使用一个编译字将断言无效化，所以当你的产品在提交给用户之后还需要继续收集错误信息时，请使用其他方式。

上面断言函数定义中用到的 `@autoclosure` 属性，使用这种属性的参数意味着我们可以在这个参数的位置传入一个表达式，这个表达式会被自动封包成一个闭包，这也正是其字面的意思：”自动闭包“。

下面列出几种断言的使用场景：

+ 验证参数的合法性
+ 将要使用一个对象，但是不确定其是否已经正确创建
+ 数组或者其他集合类、字典等复杂数据类型下标没有处于安全范围导致可能会越界
+ `assert` 函数的条件表达式参数最好一次只判断一个条件，因为如果判断多个条件，当断言被触发时，往往会无法直观地判断到底是哪一个条件未被满足。

